name: Workflow2
on:
  workflow_run:
    workflows: ['CI', 'Workflow1']
    types: [completed]
    branches: ['main']
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Verify Output
        run: |
          echo workflow_2 done,
          echo $GITHUB_OUTPUT
